#Requires -Version 7.0
function Invoke-ExportCommand
{
    # One dispatch path for every cmdlet - Get-Label (needs -IncludeDetailedLabelActions),
    # the two paged reporting cmdlets, and everything else - replacing three separate loops
    # that each duplicated the same try/catch/result-object shape.
    [CmdletBinding()]
    [OutputType([pscustomobject])]
    param(
        [Parameter(Mandatory)]
        [string]$CmdletName,
        [Parameter(Mandatory)]
        [hashtable]$Spec,
        [Parameter(Mandatory)]
        [string]$OutputPath
    )

    try
    {
        $data = if ($Spec.Paged)
        {
            Get-PagedReportData -CmdletName $CmdletName -PageSize $Spec.PageSize -AdditionalParameters $Spec.AdditionalParameters
        }
        else
        {
            $additionalParams = $Spec.AdditionalParameters
            @(& $CmdletName @additionalParams -ErrorAction Stop)
        }

        if (@($data).Count -gt 0)
        {
            Write-Verbose "Exporting data generated by $CmdletName"
            $wasExported = Export-ComplianceDataFile -CmdletName $CmdletName -Data $data -Destination $OutputPath
            return [pscustomobject]@{ Command = $CmdletName; RecordCount = @($data).Count; Exported = $wasExported }
        }
        Write-Warning "No data generated by $CmdletName"
        return [pscustomobject]@{ Command = $CmdletName; RecordCount = 0; Exported = $false }
    }
    catch [System.Management.Automation.CommandNotFoundException]
    {
        # Security & Compliance PowerShell only exposes a cmdlet in the session if the
        # connected account's role assignment grants it. A missing cmdlet is a normal,
        # per-tenant/per-role condition here, not a script failure.
        Write-Warning "$CmdletName is not available to the connected account (likely requires an additional admin role, or the underlying feature isn't licensed/enabled). Skipping."
        return [pscustomobject]@{ Command = $CmdletName; RecordCount = 0; Exported = $false }
    }
    catch
    {
        Write-Error -Message "$CmdletName failed: $($_.Exception.Message)"
        return [pscustomobject]@{ Command = $CmdletName; RecordCount = 0; Exported = $false }
    }
}
